version: "3.9"

services:
  jami-web:
    image: jami-web
    build: .
    volumes:
      # Add bind mounts for hot-reload
      - ./client:/web-client/client
      - ./routes:/web-client/routes
      - ./model:/web-client/model
      # Ignore folders from the bind mounts
      - /web-client/client/node_modules/
      - /web-client/node_modules/
      - /web-client/dist/
      - /web-client/client/dist
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on:
      - jami-daemon

  jami-daemon:
    image: jami-daemon
    build:
      context: ./daemon
      args:
        config_args: "--with-nodejs"
