version: "3.9"

services:
  jami-web:
    image: jami-web
    build: .
    volumes:
      # Add bind mounts for hot-reload
      - ./client/src:/web-client/client/src
      - ./server/src:/web-client/server/src
    ports:
      - "3001:3001"
      - "3000:3000"
      - "5000:5000"
    stdin_open: true
    depends_on:
      - jami-daemon

  jami-daemon:
    image: jami-daemon
    build:
      context: ./daemon
      args:
        config_args: "--with-nodejs"
